### PR TITLE
Environment, script

### LINKED ISSUE #8: Dev enviroment
Add package.json, jest for testing, dev deps, and linter

### PR DESCRIPTION
**Pull request by rthomazel**
fix #8

### CODE REVIEW

**Comment by rthomazel** [comment]
Added linter, formatter, configured jest and commit hooks for linting and formatting on commit.

**Comment by rthomazel** [comment]
fix #10 

See file `src/bootstrap.ts` for script implementation. Amplify requires interaction by default to set up, I think this is fine for now, although `expect` could work to automate it, but I'm not sure, kinda complex.

To test the script:
- clone repo
- `npm install`
- npm run dev

It will execute the script in your terminal. 
Passing the name of the app using the command line is supported. `npm run dev myApp`
Flags `-h` and `--help` are supported.

still working on amplify & steps after that, think we can get a basic version going pretty soon

**Review by DCarper — CHANGES_REQUESTED** [review]
Hey thanks for this, lookin great overall.

Something seems weird with `npm install`, appears to infinitely loop in `yarn postinstall`

For now requesting that we just use npm because it comes standard with node, and come back to this post-mvp

**Comment by DCarper** [comment]
> See file `src/bootstrap.ts` for script implementation. Amplify requires interaction by default to set up, I think this is fine for now, although `expect` could work to automate it, but I'm not sure, kinda complex.

Lets keep thinking about this. My thought at this point is that would be building a wrapper for Amplify itself which I think should be beyond the scope of _craaa_, devs will still need to learn and use `amplify-cli` for ongoing development.

We need a good vision statement for this package...

**Comment by rthomazel** [comment]
[install loop and yarn removed here](https://github.com/develop-mental-llc/create-react-admin-amplify-app/pull/9/commits/7f72ba860a495e62581dae177eff10704dae2333)

fix #11 
just need to add webpack now

**Comment by rthomazel** [comment]
Ok, this should be the early MVP with the happy path working. To test

```
To test the script:
- clone repo
- `npm install`
- npm run dev
```

expect to cd to project, run `npm run start` and it should show the RAA dashboard.

**Review by DCarper — COMMENTED** [review]
Definitely seeing a place for amplify app templates so that the dev doesn't need to go through the `amplify init` dialog.

**Review by DCarper — COMMENTED** [review]
I got an error running `npm install`

```cannot read property 'match' of undefined npm```

Deleting _package-lock_ and _node_modules_ then re-running `npm-install` got everything installed without error, I'm actually fine leaving this as an issue for MDP

**Review by DCarper — CHANGES_REQUESTED** [review]
We should create the app outside of the repo to avoid weirdness with git and npm, for now installing it in the directory containing the craaa repo would be great

**Review by DCarper — CHANGES_REQUESTED** [review]
The resulting app is looking great, one thing that's weird is that it has both a `package-lock.json` and a `yarn.lock`.

Can we please remove anything to do with yarn? It needs to either be one or the other, everyone is familiar with npm, only yarn people are familiar with yarn.

I could see adding optional yarn support a future release but personally not seeing it yet even in MDP because the Yarn people know how to set Yarn up easily enough where there's other bases and pain points much less covered atm.

**Comment by rthomazel** [comment]
> We should create the app outside of the repo to avoid weirdness with git and npm, for now installing it in the directory containing the craaa repo would be great

We currently use create-react-app to make the folder and the bulk of the files, so I think that's already how it works OR I'm misunderstanding.

> Can we please remove anything to do with yarn?

~yep, my bad.~ The lock file is not in the PR nor on my local repo, must be local to you then. Yarn's future is a bit gray right now, some influential devs in the JS community even declared it `dead`... shame though, really good cli

**Pull request closed without merging**
